[package]
name = "conjoined_compilation_multiprocess_model"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = "0.1.13"
bevy = {git = "https://github.com/bevyengine/bevy.git", rev = "a036b6568e2a0f295e4235003475f4686801b3b5", features = ["bevy_remote"]}
